#spring.application.name=Cards

spring:
  application:
    name: Cards-MicroService
    version: v1
    #    MySQL Databse Connection properties
  datasource:
    url: jdbc:mysql://localhost:3306/${DATABASE_NAME:eazybank_microservices}
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    Jpa Connection Properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
