
spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.1"

cards:
  message: "Welcome to Cards Services related QA APIs "
  contactDetails:
    name: "Michael Trowe - Product Owner"
    email: "michael.trowe@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345